### ISSUE TITLE
Hardcoded FTP Server IP

### ISSUE THREAD

**Issue by Baikuya** [secvulture/dvta#1]
In Line 49 in the Admin.cs Class the IP Address for the FTP Server is hardcoded. It would be nice to set the FTP Server IP on the DVTA.exe.config.

**Comment by Garcel** [comment]
In fact maybe it should be kept hardcoded and added to the list of vulnerabilities of the app.

**Comment by secvulture** [comment]
This issue is fixed in version 2.0, which is available at https://github.com/srini0x00/dvta

**Comment by secvulture** [comment]
This issue is fixed in version 2.0, which is available at https://github.com/srini0x00/dvta
